apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-apache-service
spec:
  selector:
    app: apache
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.apache.service.port }}
      targetPort: {{ .Values.apache.service.targetPort }}
